// <auto-generated />
using System;
using Fuse8_ByteMinds.SummerSchool.InternalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fuse8_ByteMinds.SummerSchool.InternalApi.Migrations
{
    [DbContext(typeof(InternalApiDbContext))]
    partial class InternalApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cur")
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fuse8_ByteMinds.SummerSchool.InternalApi.Data.Entities.Currency", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<int>("BaseCurrencyCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("base_currency_code_id");

                    b.Property<int>("CurrencyCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_code_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("DateTime", "BaseCurrencyCodeId", "CurrencyCodeId")
                        .HasName("pk_currencies");

                    b.HasIndex("BaseCurrencyCodeId")
                        .HasDatabaseName("ix_currencies_base_currency_code_id");

                    b.HasIndex("CurrencyCodeId")
                        .HasDatabaseName("ix_currencies_currency_code_id");

                    b.ToTable("currencies", "cur");
                });

            modelBuilder.Entity("Fuse8_ByteMinds.SummerSchool.InternalApi.Data.Entities.CurrencyCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_currency_codes");

                    b.ToTable("currency_codes", "cur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "aed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "afn"
                        },
                        new
                        {
                            Id = 4,
                            Name = "all"
                        },
                        new
                        {
                            Id = 5,
                            Name = "amd"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ang"
                        },
                        new
                        {
                            Id = 7,
                            Name = "aoa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "arb"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ars"
                        },
                        new
                        {
                            Id = 10,
                            Name = "aud"
                        },
                        new
                        {
                            Id = 11,
                            Name = "avax"
                        },
                        new
                        {
                            Id = 12,
                            Name = "awg"
                        },
                        new
                        {
                            Id = 13,
                            Name = "azn"
                        },
                        new
                        {
                            Id = 14,
                            Name = "bam"
                        },
                        new
                        {
                            Id = 15,
                            Name = "bbd"
                        },
                        new
                        {
                            Id = 16,
                            Name = "bdt"
                        },
                        new
                        {
                            Id = 17,
                            Name = "bgn"
                        },
                        new
                        {
                            Id = 18,
                            Name = "bhd"
                        },
                        new
                        {
                            Id = 19,
                            Name = "bif"
                        },
                        new
                        {
                            Id = 20,
                            Name = "bmd"
                        },
                        new
                        {
                            Id = 21,
                            Name = "bnb"
                        },
                        new
                        {
                            Id = 22,
                            Name = "bnd"
                        },
                        new
                        {
                            Id = 23,
                            Name = "bob"
                        },
                        new
                        {
                            Id = 24,
                            Name = "brl"
                        },
                        new
                        {
                            Id = 25,
                            Name = "bsd"
                        },
                        new
                        {
                            Id = 26,
                            Name = "btc"
                        },
                        new
                        {
                            Id = 27,
                            Name = "btn"
                        },
                        new
                        {
                            Id = 28,
                            Name = "busd"
                        },
                        new
                        {
                            Id = 29,
                            Name = "bwp"
                        },
                        new
                        {
                            Id = 30,
                            Name = "byn"
                        },
                        new
                        {
                            Id = 31,
                            Name = "byr"
                        },
                        new
                        {
                            Id = 32,
                            Name = "bzd"
                        },
                        new
                        {
                            Id = 33,
                            Name = "cad"
                        },
                        new
                        {
                            Id = 34,
                            Name = "cdf"
                        },
                        new
                        {
                            Id = 35,
                            Name = "chf"
                        },
                        new
                        {
                            Id = 36,
                            Name = "clf"
                        },
                        new
                        {
                            Id = 37,
                            Name = "clp"
                        },
                        new
                        {
                            Id = 38,
                            Name = "cny"
                        },
                        new
                        {
                            Id = 39,
                            Name = "cop"
                        },
                        new
                        {
                            Id = 40,
                            Name = "crc"
                        },
                        new
                        {
                            Id = 41,
                            Name = "cuc"
                        },
                        new
                        {
                            Id = 42,
                            Name = "cup"
                        },
                        new
                        {
                            Id = 43,
                            Name = "cve"
                        },
                        new
                        {
                            Id = 44,
                            Name = "czk"
                        },
                        new
                        {
                            Id = 45,
                            Name = "dai"
                        },
                        new
                        {
                            Id = 46,
                            Name = "djf"
                        },
                        new
                        {
                            Id = 47,
                            Name = "dkk"
                        },
                        new
                        {
                            Id = 48,
                            Name = "dop"
                        },
                        new
                        {
                            Id = 49,
                            Name = "dot"
                        },
                        new
                        {
                            Id = 50,
                            Name = "dzd"
                        },
                        new
                        {
                            Id = 51,
                            Name = "egp"
                        },
                        new
                        {
                            Id = 52,
                            Name = "ern"
                        },
                        new
                        {
                            Id = 53,
                            Name = "etb"
                        },
                        new
                        {
                            Id = 54,
                            Name = "eth"
                        },
                        new
                        {
                            Id = 55,
                            Name = "eur"
                        },
                        new
                        {
                            Id = 56,
                            Name = "fjd"
                        },
                        new
                        {
                            Id = 57,
                            Name = "fkp"
                        },
                        new
                        {
                            Id = 58,
                            Name = "gbp"
                        },
                        new
                        {
                            Id = 59,
                            Name = "gel"
                        },
                        new
                        {
                            Id = 60,
                            Name = "ggp"
                        },
                        new
                        {
                            Id = 61,
                            Name = "ghs"
                        },
                        new
                        {
                            Id = 62,
                            Name = "gip"
                        },
                        new
                        {
                            Id = 63,
                            Name = "gmd"
                        },
                        new
                        {
                            Id = 64,
                            Name = "gnf"
                        },
                        new
                        {
                            Id = 65,
                            Name = "gtq"
                        },
                        new
                        {
                            Id = 66,
                            Name = "gyd"
                        },
                        new
                        {
                            Id = 67,
                            Name = "hkd"
                        },
                        new
                        {
                            Id = 68,
                            Name = "hnl"
                        },
                        new
                        {
                            Id = 69,
                            Name = "hrk"
                        },
                        new
                        {
                            Id = 70,
                            Name = "htg"
                        },
                        new
                        {
                            Id = 71,
                            Name = "huf"
                        },
                        new
                        {
                            Id = 72,
                            Name = "idr"
                        },
                        new
                        {
                            Id = 73,
                            Name = "ils"
                        },
                        new
                        {
                            Id = 74,
                            Name = "imp"
                        },
                        new
                        {
                            Id = 75,
                            Name = "inr"
                        },
                        new
                        {
                            Id = 76,
                            Name = "iqd"
                        },
                        new
                        {
                            Id = 77,
                            Name = "irr"
                        },
                        new
                        {
                            Id = 78,
                            Name = "isk"
                        },
                        new
                        {
                            Id = 79,
                            Name = "jep"
                        },
                        new
                        {
                            Id = 80,
                            Name = "jmd"
                        },
                        new
                        {
                            Id = 81,
                            Name = "jod"
                        },
                        new
                        {
                            Id = 82,
                            Name = "jpy"
                        },
                        new
                        {
                            Id = 83,
                            Name = "kes"
                        },
                        new
                        {
                            Id = 84,
                            Name = "kgs"
                        },
                        new
                        {
                            Id = 85,
                            Name = "khr"
                        },
                        new
                        {
                            Id = 86,
                            Name = "kmf"
                        },
                        new
                        {
                            Id = 87,
                            Name = "kpw"
                        },
                        new
                        {
                            Id = 88,
                            Name = "krw"
                        },
                        new
                        {
                            Id = 89,
                            Name = "kwd"
                        },
                        new
                        {
                            Id = 90,
                            Name = "kyd"
                        },
                        new
                        {
                            Id = 91,
                            Name = "kzt"
                        },
                        new
                        {
                            Id = 92,
                            Name = "lak"
                        },
                        new
                        {
                            Id = 93,
                            Name = "lbp"
                        },
                        new
                        {
                            Id = 94,
                            Name = "lkr"
                        },
                        new
                        {
                            Id = 95,
                            Name = "lrd"
                        },
                        new
                        {
                            Id = 96,
                            Name = "lsl"
                        },
                        new
                        {
                            Id = 97,
                            Name = "ltc"
                        },
                        new
                        {
                            Id = 98,
                            Name = "ltl"
                        },
                        new
                        {
                            Id = 99,
                            Name = "lvl"
                        },
                        new
                        {
                            Id = 100,
                            Name = "lyd"
                        },
                        new
                        {
                            Id = 101,
                            Name = "mad"
                        },
                        new
                        {
                            Id = 102,
                            Name = "matic"
                        },
                        new
                        {
                            Id = 103,
                            Name = "mdl"
                        },
                        new
                        {
                            Id = 104,
                            Name = "mga"
                        },
                        new
                        {
                            Id = 105,
                            Name = "mkd"
                        },
                        new
                        {
                            Id = 106,
                            Name = "mmk"
                        },
                        new
                        {
                            Id = 107,
                            Name = "mnt"
                        },
                        new
                        {
                            Id = 108,
                            Name = "mop"
                        },
                        new
                        {
                            Id = 109,
                            Name = "mro"
                        },
                        new
                        {
                            Id = 110,
                            Name = "mur"
                        },
                        new
                        {
                            Id = 111,
                            Name = "mvr"
                        },
                        new
                        {
                            Id = 112,
                            Name = "mwk"
                        },
                        new
                        {
                            Id = 113,
                            Name = "mxn"
                        },
                        new
                        {
                            Id = 114,
                            Name = "myr"
                        },
                        new
                        {
                            Id = 115,
                            Name = "mzn"
                        },
                        new
                        {
                            Id = 116,
                            Name = "nad"
                        },
                        new
                        {
                            Id = 117,
                            Name = "ngn"
                        },
                        new
                        {
                            Id = 118,
                            Name = "nio"
                        },
                        new
                        {
                            Id = 119,
                            Name = "nok"
                        },
                        new
                        {
                            Id = 120,
                            Name = "npr"
                        },
                        new
                        {
                            Id = 121,
                            Name = "nzd"
                        },
                        new
                        {
                            Id = 122,
                            Name = "omr"
                        },
                        new
                        {
                            Id = 123,
                            Name = "op"
                        },
                        new
                        {
                            Id = 124,
                            Name = "pab"
                        },
                        new
                        {
                            Id = 125,
                            Name = "pen"
                        },
                        new
                        {
                            Id = 126,
                            Name = "pgk"
                        },
                        new
                        {
                            Id = 127,
                            Name = "php"
                        },
                        new
                        {
                            Id = 128,
                            Name = "pkr"
                        },
                        new
                        {
                            Id = 129,
                            Name = "pln"
                        },
                        new
                        {
                            Id = 130,
                            Name = "pyg"
                        },
                        new
                        {
                            Id = 131,
                            Name = "qar"
                        },
                        new
                        {
                            Id = 132,
                            Name = "ron"
                        },
                        new
                        {
                            Id = 133,
                            Name = "rsd"
                        },
                        new
                        {
                            Id = 134,
                            Name = "rub"
                        },
                        new
                        {
                            Id = 135,
                            Name = "rwf"
                        },
                        new
                        {
                            Id = 136,
                            Name = "sar"
                        },
                        new
                        {
                            Id = 137,
                            Name = "sbd"
                        },
                        new
                        {
                            Id = 138,
                            Name = "scr"
                        },
                        new
                        {
                            Id = 139,
                            Name = "sdg"
                        },
                        new
                        {
                            Id = 140,
                            Name = "sek"
                        },
                        new
                        {
                            Id = 141,
                            Name = "sgd"
                        },
                        new
                        {
                            Id = 142,
                            Name = "shp"
                        },
                        new
                        {
                            Id = 143,
                            Name = "sll"
                        },
                        new
                        {
                            Id = 144,
                            Name = "sol"
                        },
                        new
                        {
                            Id = 145,
                            Name = "sos"
                        },
                        new
                        {
                            Id = 146,
                            Name = "srd"
                        },
                        new
                        {
                            Id = 147,
                            Name = "std"
                        },
                        new
                        {
                            Id = 148,
                            Name = "svc"
                        },
                        new
                        {
                            Id = 149,
                            Name = "syp"
                        },
                        new
                        {
                            Id = 150,
                            Name = "szl"
                        },
                        new
                        {
                            Id = 151,
                            Name = "thb"
                        },
                        new
                        {
                            Id = 152,
                            Name = "tjs"
                        },
                        new
                        {
                            Id = 153,
                            Name = "tmt"
                        },
                        new
                        {
                            Id = 154,
                            Name = "tnd"
                        },
                        new
                        {
                            Id = 155,
                            Name = "top"
                        },
                        new
                        {
                            Id = 156,
                            Name = "try"
                        },
                        new
                        {
                            Id = 157,
                            Name = "ttd"
                        },
                        new
                        {
                            Id = 158,
                            Name = "twd"
                        },
                        new
                        {
                            Id = 159,
                            Name = "tzs"
                        },
                        new
                        {
                            Id = 160,
                            Name = "uah"
                        },
                        new
                        {
                            Id = 161,
                            Name = "ugx"
                        },
                        new
                        {
                            Id = 162,
                            Name = "usd"
                        },
                        new
                        {
                            Id = 163,
                            Name = "usdc"
                        },
                        new
                        {
                            Id = 164,
                            Name = "usdt"
                        },
                        new
                        {
                            Id = 165,
                            Name = "uyu"
                        },
                        new
                        {
                            Id = 166,
                            Name = "uzs"
                        },
                        new
                        {
                            Id = 167,
                            Name = "vef"
                        },
                        new
                        {
                            Id = 168,
                            Name = "vnd"
                        },
                        new
                        {
                            Id = 169,
                            Name = "vuv"
                        },
                        new
                        {
                            Id = 170,
                            Name = "wst"
                        },
                        new
                        {
                            Id = 171,
                            Name = "xaf"
                        },
                        new
                        {
                            Id = 172,
                            Name = "xag"
                        },
                        new
                        {
                            Id = 173,
                            Name = "xau"
                        },
                        new
                        {
                            Id = 174,
                            Name = "xcd"
                        },
                        new
                        {
                            Id = 175,
                            Name = "xdr"
                        },
                        new
                        {
                            Id = 176,
                            Name = "xof"
                        },
                        new
                        {
                            Id = 177,
                            Name = "xpd"
                        },
                        new
                        {
                            Id = 178,
                            Name = "xpf"
                        },
                        new
                        {
                            Id = 179,
                            Name = "xpt"
                        },
                        new
                        {
                            Id = 180,
                            Name = "xrp"
                        },
                        new
                        {
                            Id = 181,
                            Name = "yer"
                        },
                        new
                        {
                            Id = 182,
                            Name = "zar"
                        },
                        new
                        {
                            Id = 183,
                            Name = "zmk"
                        },
                        new
                        {
                            Id = 184,
                            Name = "zmw"
                        },
                        new
                        {
                            Id = 185,
                            Name = "zwl"
                        });
                });

            modelBuilder.Entity("Fuse8_ByteMinds.SummerSchool.InternalApi.Data.Entities.Currency", b =>
                {
                    b.HasOne("Fuse8_ByteMinds.SummerSchool.InternalApi.Data.Entities.CurrencyCode", "BaseCurrencyCode")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currencies_currency_codes_base_currency_code_id");

                    b.HasOne("Fuse8_ByteMinds.SummerSchool.InternalApi.Data.Entities.CurrencyCode", "CurrencyCode")
                        .WithMany()
                        .HasForeignKey("CurrencyCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currencies_currency_codes_currency_code_id");

                    b.Navigation("BaseCurrencyCode");

                    b.Navigation("CurrencyCode");
                });
#pragma warning restore 612, 618
        }
    }
}
